### ISSUE TITLE
Creating tables/feature classes with protected keywords

### ISSUE THREAD

**Issue by CF-FHB-X** [realiii/fudgeo#10]
Me again! Found one last issue. If someone creates a feature class or table that uses one of the SQLite keywords (see https://www.sqlite.org/lang_keywords.html for the full list), the following error is thrown (in this case using `or` as the feature class name):
```
sqlite3.OperationalError: near "or": syntax error
```

While it's probably not a good idea to use those keywords, users will find a way to break that! In fact, it is possible to create tables with those keywords - you just need to quote the table name in the `CREATE TABLE` statements. For example, you can change the `CREATE_FEATURE_TABLE` SQL in `fudgeo` (https://github.com/realiii/fudgeo/blob/def68ecbbe25c63e9ddca72b15b3719006a81bf8/fudgeo/sql.py#L61) to this:

```python
CREATE_FEATURE_TABLE = """
    CREATE TABLE '{name}' (
        fid INTEGER not null primary key autoincrement, 
        SHAPE {feature_type}{other_fields})
"""
```
(just quoted the table name)

Either that or find a way of checking for those keywords beforehand, but I can't seem to find a way to do that from the `sqlite3` library. There are routines that can do that in sqlite (see https://www.sqlite.org/c3ref/keyword_check.html), but I have no clue how to access them from Python.

**Comment by jlhumber** [comment]
Marking as won't implement, you can protect against this in your code to avoid creation of such tables or column names
