### ISSUE TITLE
Deleting Feature Classes

### ISSUE THREAD

**Issue by CF-FHB-X** [realiii/fudgeo#6]
Hi there!

I just got `fudgeo` incorporated into a package we've been developing, and it's working like a charm. I did have a question regarding overwriting feature classes, though. If we're passing in a list of datasets to write out to GPKG, but there's already a feature class with that name in the GPKG, we get a `table [name] already exists" error. Is there a way to either possibly overwrite a feature class, or delete the existing one? Not sure if something along the lines of this would work:
```python
gpkg = GeoPackage(r'c:\data\example.gpkg')
cursor = gpkg.connection.execute(
    """DROP TABLE test""")
cursor.commit()
```
Are there any other support tables that would get affected if we went this route?

**Comment by jlhumber** [comment]
Hey @CF-FHB-X, 

Just using the DROP statement would leave around triggers and related records in the internal tables.  We'll add in the following to `v0.1.2`:

- an overwrite option on the `create_feature_class` and `create_table` methods (as well as on the `create` class methods on `FeatureClass` and `Table`.   
- `drop` methods on the `FeatureClass` and `Table` classes

**Comment by CF-FHB-X** [comment]
Could we also add an option to update the bounding coords in the gpkg_contents table as well? That would allow the "zoom to layer" functionality to work in things like QGIS and ArcGIS.

**Comment by jlhumber** [comment]
@CF-FHB-X v0.1.2 is now on pypi

**Comment by CF-FHB-X** [comment]
Thanks! Quickest turnaround ever for a feature request!
