### ISSUE TITLE
GeoPackage Vector Tiles (PBF/MVT)

### ISSUE THREAD

**Issue by techmavengeospatial** [realiii/fudgeo#65]
using OGC Extensions to GPKG
support vector tiles

Gpkg_extensions
[Gpkgext_vt_layers](https://gitlab.com/imagemattersllc/ogc-vtp2/-/blob/master/extensions/1-vte.adoc)
[Gpkgext_vt_fields](https://gitlab.com/imagemattersllc/ogc-vtp2/-/blob/master/extensions/1-vte.adoc)
[Im_vector_tiles_mapbox](https://gitlab.com/imagemattersllc/ogc-vtp2/-/blob/master/extensions/4-vtae.adoc)

Optional reference attributes stored in regular attribute table
Gpkgext_relations [extensions/4-vtae.adoc · master · Image Matters LLC / ogc-vtp2 · GitLab](https://gitlab.com/imagemattersllc/ogc-vtp2/-/blob/master/extensions/4-vtae.adoc)

https://github.com/opengeospatial/OGC-OS-Sprint-04-2020/tree/master/Shared_Datasets 
https://github.com/jerstlouis/developer-events/blob/patch-1/2023/Tiling-Interfaces-Code-Sprint/README.md 

https://github.com/jerstlouis/developer-events/blob/patch-1/2023/Tiling-Interfaces-Code-Sprint/GeoPackage%20Vector%20Tiles%20Extensions.pdf 
https://onedrive.live.com/?id=DF6BA22C128FC0D6%217140&cid=DF6BA22C128FC0D6 
http://opengeospatial.github.io/e-learning/ogcapi-tiles/text/basic-index.html

Sample GPKG vector tiles
https://drive.google.com/drive/folders/15sBdCM1nenzLst-fIjGyLdzZKhyxZI9m

**Comment by jlhumber** [comment]
It appears that vector tiles are only part of the Community Extensions and not the official geopackage specification, in this package we are only looking to add official extensions.  If someone wishes to contribute suitable code for a community extension then we would consider including it.
